public-resources:
  3dpricey-staging:
    name: 3DPricey Staging
    protocol: http
    full-domain: staging.printel.ro
    targets:
      - hostname: backend
        port: 3001
        method: http
        path: /api
        path-match: prefix
        priority: 10
      - hostname: frontend
        port: 80
        method: http
        path: /
        path-match: prefix
        priority: 100
